### ISSUE TITLE
Nach WebRTC Grundlagen suchen

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#1]
- Grundlagen zur Funktionalitaet und Anwendung von WebRTC herausarbeiten
- Praestentation am Dienstag

**Comment by kvbx** [comment]
Ich probiere noch ein wenig rum mehrere Leute einzutragen. Ein Issue kann immer nur einer Person zugewiesen werden. @yahya-zamani hatte sich als erster gemeldet, daher kriegt er dieses, @Nilay10  sollte jetzt aber auch als Participant eingetragen worden sein.

**Comment by yahya-zamani** [comment]
Ist sogut wie fertig.
