### ISSUE TITLE
Installationsmanual Kurento Server

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#10]
Falls bei #9 abweichungen vom offiziellen Installationsmanual aufgetreten sind bitte eine Kurze Dokumentation ins Wiki

**Comment by kvbx** [comment]
Bitte Format fuer's Wiki beachten. Das kann kein Word.

**Comment by andy069** [comment]
Wenn ihr fertig seit könnt ihr mir es schicken.
