### ISSUE TITLE
SSL Zertifikat erstellen

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#13]
Der  Webserver soll via SSL erreichbar sein. Im Idealfall sollte das Zertifikat in allen Browsern per default gültig sein ("Let's encrypt"). Wenn das nicht möglich ist geht auch ein self-signed.

**Comment by kvbx** [comment]
Zusammen mit @githubmath5

**Comment by AlexS05** [comment]
Wenn wir ein SSL-Zertifikat über längere Zeit haben wollen, müssen wir Let's Encrypt verwenden.
Aber das Programm kann/soll nur der Server-Admin ausführen. Besitzen wir diese ServerAdmin-rechte (Let's Encrypt identifiziert ihn über Public/Private Key) oder an wen muss ich mich da richten?

**Comment by AlexS05** [comment]
Info's dazu:
https://letsencrypt.org/how-it-works/
https://letsencrypt.org/getting-started/

**Comment by kvbx** [comment]
Ich hab auch ne andere Domain, die wir dazu benutzen koennen. Die hab ich extra fuer so Entwicklungskram, wenn man die schnell und oft eingeben muss. Und momentan brauch ich die nicht.

asdfjkl.de
