### ISSUE TITLE
Tutorial 1 Seite

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#18]
HTML Dokument. Wird spaeter in Spring eingepflegt

- Ueberschrift "Tutorial 1: Hello World"
- zwei Platzhalter Videoelemente
- Start Button
- Stop Button

**Comment by andy069** [comment]
HTML Datei und css datei sind in dropbox drinne.
Es sind 2 Videos drinne. 
Ihr könnt einfach test.mp4 unter source für euer eigenes video ersetzen.
Zum Testen ob das Video klappt kann man im video tag "controls" eingeben und man kann dann das Video abspielen.
Falls das Video nicht abspielt ist euer Browser veraltet oder er unterstützt nicht HTML5
Die Buttons "play" und "stop" sind drinne und müssen mit javascript programmiert werden.

**Comment by kvbx** [comment]
Sorry, Dropbox zaehlt nicht. Was nicht im Git ist existiert nicht. Mach alles im Git in `/src/main/resources/static/`. Der Ordner existiert noch nicht, den musst du erstellen. So, dass dann `src/main/resources/static/foobar.html`

**Comment by kvbx** [comment]
Ach, das Testvideo muss nicht nach git. Anforderung waren nur zwei Platzhalter, also leere Elemente. Das macht sonst das Repository so gross. :-D

**Comment by andy069** [comment]
Testvideo war eher als Platzhalter gedacht wer Videos reinmachen will xD
Ok mach ich dann noch.
Soll ich die Position der Videos noch ändern wie beim Tutorial ?

**Comment by andy069** [comment]
Ok fertig.
Die Ordner sind erstellt.
In dem static Ordner sind: .html Datei,.css Datei und ein Bild was als Poster dient falls
nichts abgespielt wird.

**Comment by kvbx** [comment]
HTML Validierung mit https://validator.w3.org/ failed (2 Warnings, 2 Errors)
CSS Validierung mit https://jigsaw.w3.org/css-validator/validator failed (2 Errors)

**Comment by andy069** [comment]
liegt wahrscheinlich an "test.mp4"
weil ich das video nicht geschickt hab oder?

**Comment by kvbx** [comment]
Nee, im HTML fehlt beispielsweise nen Anfuehrungszeichen, im CSS nen Buchstabe 'p'

**Comment by andy069** [comment]
ahhh ok eben gefunden xD
Verbessere das mal schnell

**Comment by andy069** [comment]
was für eine adresse muss ich beim w3c markup validator angeben um zu gucken ob alles stimmt?

**Comment by andy069** [comment]
ah ok habs gefunden :D

**Comment by andy069** [comment]
So es gibt keine Fehlermeldung mehr :)

**Comment by salekseev73** [comment]
Die Seite auf den Server kopieren.

**Comment by salekseev73** [comment]
https://asdfjkl.de/kurento_tutorial1.html
