### ISSUE TITLE
Coding standards entwickeln

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#29]
z.B. Indention Spaces/Tabs, deutsch/englisch, Braces in neuer Zeile, etc

**Comment by AlexS05** [comment]
[Coding_Standards_(WIP).docx](https://github.com/Alekseev-Projekt/Projekt/files/267362/Coding_Standards_.WIP.docx)

Nicht viel zurzeit, werde es aber noch weiter ausbauen.

**Comment by kvbx** [comment]
muss nur noch in's Wiki geladen werden
