### ISSUE TITLE
Spring Template Engine auswaehlen

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#31]
Welche Template Engines sind fuer Spring verfuegbar? Bitte evaluieren und eventuell kleine Beispiele ins Wiki. Es soll moeglich sein Views zu verschachteln.

**Comment by Nilay10** [comment]
Spring beinhaltet folgende Template Engines. 
FreeMarker,Groovy,Thymeleaf,Velocity und Mustache.

Hier findet man eine tolle Zusammenfassung über das Template Thymeleaf.
-> www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#creating-and-configuring-the-template-engine

Hier auch ein genaues Beispiel mit dem Template Thymeleaf, hab zwei Seiten die ich ganz gut finde :)
-> https://springframework.guru/spring-boot-web-application-part-2-using-thymeleaf/
-> http://jvmhub.com/2015/07/19/spring-boot-with-thymeleaf-tutorial/
