### ISSUE TITLE
Entwicklungsumgebungen evaluieren und präsentieren

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#5]
Wir werden Web-Entwicklung betreiben und Serverseitig Java/Node.js verwenden.

**Comment by kvbx** [comment]
Vorschlag: IntelliJ Idea (Web, Java, NodeJS)
Favorit von @yahya-zamani und mir, die Ultimate Edition bekommen wir als Studenten kostenlos

Schaut euch mal WebStorm an. Ich denke, die kriegen wir auch kostenlos. Kann Web und NodeJS glaube ich.

**Comment by Oguz90** [comment]
ich stimme dem Vorschlag zu.

**Comment by yahya-zamani** [comment]
Finde ich cool!

**Comment by kvbx** [comment]
Entscheidung für Intellij getroffen.
