### ISSUE TITLE
Git Präsentation und Tutorial vorbereiten

### ISSUE THREAD

**Issue by kvbx** [Alekseev-Projekt/Projekt#6]
Wir brauchen ein paar Git Profis.

- Einarbeiten in Git (Was sind Branches, Remotes, Merges, Repositories, Subprojects)
- Einrichten von Git
- Benutzen von Git (CLI und IDE-GUI)

**Comment by kvbx** [comment]
Schaut euch mal das hier an: https://guides.github.com/activities/hello-world/

**Comment by Steveburn88** [comment]
Dank dir, ich schau heute Abend schon mal rein, werde aber erst am Samstag dazu kommen.
